config/routes.rb
Rails.application.routes.draw do

  devise_for :users, sign_out_via: [:get, :post, :delete], controllers: {
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions",
  }
  as :user do
    get 'users', :to => 'users/registrations#edit', :as => :user_root # Rails 3
    get '/user/edit(.format)', to: 'users/registrations#edit', defaults: {id: 0}
  end

  root 'home#home'

  get 'sitemap.xml' => 'home#sitemap', defaults:{format: :xml}

  get 'privacy.html' => 'home#privacy', defaults:{format: :html}

  get 'tos.html' => 'home#tos', defaults:{format: :html}

  get 'fuzzy_find.json' => 'home#fuzzy_find', defaults:{format: :json}

  get 'home/drinks.json' => 'home#drinks', defaults:{format: :json}

  get 'discover' => 'home#home', defaults:{discover: true, format: :html}

  resources :admin, only: [] do
    collection do
      get :comments
      get :ingredient_revisions
      get :photos
      get :reviews
      get :revisions
    end
    member do
      post :publish, action: 'publish'
    end
  end

  resources :comments, only: [:create, :destroy] do
    member do
      post :unvote_tip
      post :vote_tip
    end
  end

  resources :drinks do
    collection do
      get :suggestions
    end
    member do
      get :ingredients
      get :revisions
    end
  end

  resources :drinks, path: 'recipe', only: [:show]

  resources :favourites, only: [:index, :create, :update, :destroy]

  resources :favourites_collections, only: [:index, :create, :update, :destroy]
  
  resources :flags, only: :create

  resources :ingredients do
    collection do
      get :names
    end
    member do
      get :revisions
    end
  end

  resources :ingredients, path: 'ingredient', only: [:show]

  resources :ingredient_revisions, only: [:create, :show]

  resources :photos, only: [:index, :create]
  
  resources :reviews do
    collection do
      get :count
      get :next
    end
    member do
      post :vote
    end
  end

  resources :revisions, only: [:create, :show]

  resources :users, only: [:show] do
    collection do
      get :unviewed_point_distributions
      put :viewed_point_distributions
    end
    member do
      get :trophies
    end
  end

  get '/user(.format)', to: 'users#show', defaults: {id: 0}
  get '/user/trophies(.format)', to: 'users#trophies', defaults: {id: 0}

  resources :votes, only: [:create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/index.html.erb
<div class="row">
    <div class="col-lg-2"><a href="/admin/comments">Comments</a></div>    
    <div class="col-lg-2"><a href="/admin/photos">Photos</a></div>    
    <div class="col-lg-2"><a href="/admin/revisions">Revisions</a></div>    
    <div class="col-lg-2"><a href="/admin/ingredient_revisions">IngredientEdits</a></div>    
</div>

<h2><%= controller.action_name.humanize %></h2>

<div class="row">
    <div class="col-md-1" title="ID">ID</div>
    <div class="col-md-3" title="Created at"><i class="fa fa-calendar"></i></div>
    <div class="col-md-1" title="User (contributor) id"><i class="fa fa-user"></i></div>
    <div class="col-md-1" title="Status"><i class="fa fa-chart"></i></div>
</div>

<% @resources.each do |resource| %>
<div ng-controller="PatchableCtrl">
    <div class="row <%= resource.status != Flaggable::APPROVED ? 'admin-unpublished' : 'admin-published'  %>">
        <div class="col-md-1"><%= resource.id %></div>
        <div class="col-md-3"><%= resource.created_at %></div>
        <div class="col-md-1"><%= resource.user_id %> <%= resource.user.name %></div>
        <div class="col-md-1"><%= resource.status %></div>
        <div class="col-md-1">
            <% case resource.status; when Flaggable::REJECTED %>
                <%= button_to publish_admin_path(resource, klass:resource.class.name, status:resource.status), title:'publish' do %>
                    <i class="fa fa-print"></i>
                <% end %>
            <% when Flaggable::NEEDS_REVIEW %>
                <%= button_to publish_admin_path(resource, klass:resource.class.name, status:resource.status), title:'publish' do %>
                    <i class="fa fa-print"></i>
                <% end %>
            <% when Flaggable::APPROVED %>
                <%= button_to publish_admin_path(resource, klass:resource.class.name, status:resource.status), title:'unpublish' do %>
                    <i class="fa fa-print"></i>
                <% end %>
            <% end %>
        </div>
        <div class="col-md-2" style="overflow:hidden; white-space:nowrap" title="<%= admin_resource_preview_text(resource) %>">
            <% if resource.respond_to?(:url) && resource.url.present? %>
                <%= link_to "View #{resource.class.name}", resource.url %>
            <% end %>
            <% if resource.respond_to?(:drink_id) && resource.drink_id.present? %>
                <%= link_to "View Drink", drink_path(resource.drink_id) %>
            <% end -%>
            <% if resource.class < Patchable %>
                <a ng-hide="diffableLoaded" ng-click="fetchDiffable('<%=j polymorphic_path(resource, format: :json) %>')">Show Diff</a>
                <a ng-show="diffableLoaded" ng-click="diffableLoaded=false">Hide</a>
            <% end -%>
            <%= admin_resource_preview_text(resource) %>
        </div>
    </div>
    <div ng-if="diffableLoaded" ng-include="'/application/revision.html'"></div>
</div>
<% end %>

<div><%= will_paginate @resources %></div>

app/views/admin/reviews.html.erb
<div class="row">
    <div class="col-md-1" title="Review ID">RID</div>
    <div class="col-md-3" title="Review created at"><i class="fa fa-calendar"></i></div>
    <div class="col-md-2" title="Reviewable type"><i class="fa fa-object-group"></i></div>
    <div class="col-md-1" title="Reviewable id">ID</div>
    <div class="col-md-1" title="User (contributor) id"><i class="fa fa-user"></i></div>
</div>

<% @reviews.each do |review| %>
    <div class="row <%= review.open ? 'review-open' : 'review-closed'  %>">
        <div class="col-md-1"><%= review.id %></div>
        <div class="col-md-3"><%= review.created_at %></div>
        <div class="col-md-2"><%= review.reviewable_type %></div>
        <div class="col-md-1"><%= review.reviewable_id %></div>
        <div class="col-md-1"><%= review.contributor_id %></div>
    </div>
<% end %>
<div><%= will_paginate @reviews %></div>